[project]
name = "uv"
version = "0.1.0"
description = "uv のドキュメントに書いてあることを検証するためのパッケージ"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["ruff>=0.14.1"]

[project.optional-dependencies]
dev = []

[dependency-groups]
dev = ["pytest>=8.4.2"]
